### ISSUE TITLE
Working with ERP (tutorial)

### ISSUE THREAD

**Issue by alexfpm** [wmvanvliet/neuroscience_tutorials#3]
Hi Marijn!

I'm trying to run and understand the Tutorial "Loading EEG data and plotting an ERP", but I don't have the mentioned database (**tutorial1-01.mat**). Could you please share it with me?

Seems that It's necessarry for local (hard-drive) tests. Thank you!

**Comment by wmvanvliet** [comment]
https://www.dropbox.com/s/c3iwvcy12e98p58/tutorial1-01.mat?dl=0
