### ISSUE TITLE
Frequency (sample_rate) to voltage

### ISSUE THREAD

**Issue by SaeedPourjafar** [wmvanvliet/neuroscience_tutorials#4]
Dear dr. van Vliet,
From _[1. Load EEG data and plot ERP](https://github.com/wmvanvliet/neuroscience_tutorials/blob/master/eeg-bci/1.%20Load%20EEG%20data%20and%20plot%20ERP.ipynb)_ there are codes as such:
```
from_index = int(0.3 * sample_rate)
to_index = int(0.5 * sample_rate)
p300_amplitudes = mean(mean(trials[:, :, from_index:to_index], axis=1), axis=1)
```
Would you please explain how we get from proportion of sample_rate (which are now indices) to voltage? In other words, is there a way to compute voltage from frequency? 
P.S. Sorry for this basic question, any help is much appreciated.

**Comment by wmvanvliet** [comment]
You can get the voltage at a specific point in time:

```
t = 20  # 20th time point (how many seconds depends on the samplerate)
trials[0, 0, t]  # voltage for the first trial, at the first sensor, at time t
```

I don't understand what you mean by "voltage from frequency", sorry. If the above doesn't help, could you explain the question in more detail?

**Comment by SaeedPourjafar** [comment]
Thanks for your explanation I think I get it now. 
The voltages for the experiment are varying from around -60 to +80 microvolt across samples (288349) which then if we divide it by the sample rate (2048) we can get the info in seconds. Therefore the _trials_ is a set of three dimensional tensor which holds voltages at the specific trial, for a specific sensor at the desired time point.
Please correct me if I'm wrong.

**Comment by wmvanvliet** [comment]
you are correct!
