### ISSUE TITLE
Left and right hemisphere for Imagined movement

### ISSUE THREAD

**Issue by SaeedPourjafar** [wmvanvliet/neuroscience_tutorials#5]
Dear dr. van Vliet,
From [3. Imagined movement.ipynb](https://github.com/wmvanvliet/neuroscience_tutorials/blob/master/eeg-bci/3.%20Imagined%20movement.ipynb) there is a line that says:
> This is in line with the theory that the left hand is controlled by the left hemisphere...

Is this because we are talking about imagery movement and not the actual movement? Because I've read [here](https://www.verywellmind.com/left-brain-vs-right-brain-2795005#theory) that:

> The left hemisphere controls the muscles on the right side of the body while the right hemisphere controls those on the left.

 Would you please clarify it for me?

**Comment by wmvanvliet** [comment]
if it really says in my tutorial:

> This is in line with the theory that the left hand is controlled by the left hemisphere...

then that is a mistake. The left hand is indeed controlled by the right hemisphere.

**Comment by SaeedPourjafar** [comment]
> if it really says in my tutorial:
> 
> > This is in line with the theory that the left hand is controlled by the left hemisphere...
> 
> then that is a mistake. The left hand is indeed controlled by the right hemisphere.

Thank you for the clarification.
