### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by Corinamar** [wmvanvliet/neuroscience_tutorials#8]
Hello, my name is Corina and I am a student in terminal year. Can you please, tell me if you used an algorithm presented in an article for this implementation? I am referring to the imagined movement code.

**Comment by wmvanvliet** [comment]
The algorithm is called Common Spatial Patterns (CSP). Here is one of the first articles describing its use in BCI: https://ieeexplore.ieee.org/document/895946

**Comment by Corinamar** [comment]
Thank you so much! Can you please tell me if the code is only for one signal or if it is for the whole dataset? I am a beginner.

**Comment by wmvanvliet** [comment]
Could you explain a bit more about what you mean by "one signal" and "whole dataset"?

**Comment by Corinamar** [comment]
Sure. The BCI Competition IV has 10 recordings of EEG signals. I would like to know if you used only one recording or if you used all 10 recordings, especially for LDA classification.
Thank you!

**Comment by wmvanvliet** [comment]
ah, now I understand, thank you. It only uses a single recording.

**Comment by Corinamar** [comment]
Ok. Thank you so much!

**Comment by Corinamar** [comment]
Hello, I am sorry to bother you again, but could you explain why the window size is 0.5-2.5 seconds?

**Comment by wmvanvliet** [comment]
Because at that time, the event-related desynchronization (ERD) is most prominent in the EEG signal.

**Comment by Corinamar** [comment]
Thank you, I really appreciate it and I really am sorry for bothering you.
